---
- name: configure Sonarqube.properties file.
  lineinfile:
    path: /usr/local/sonar/conf/sonar.properties
    regexp: "{{item.key }}"
    line: "{{ item.key }}={{ item.value }}"
  notify: restart sonar
  with_dict: "{{ jdbc_defaults | combine(sonar_properties, recursive=True) }}"
